import { LEGAL_DOCUMENT_VERSION } from 'shared';

export enum LegalDocumentType {
  TERMS = 'TERMS',
  OFFER = 'OFFER',
  RECURRING_PAYMENT = 'RECURRING_PAYMENT',
  MARKETING = 'MARKETING',
  PRIVACY_ACKNOWLEDGEMENT = 'PRIVACY_ACKNOWLEDGEMENT',
  PERSONAL_DATA_CONSENT = 'PERSONAL_DATA_CONSENT'
}

export enum LegalAcceptanceSource {
  REGISTRATION = 'REGISTRATION',
  CHECKOUT = 'CHECKOUT',
  ACCOUNT_SETTINGS = 'ACCOUNT_SETTINGS',
  DOCUMENT_UPDATE = 'DOCUMENT_UPDATE'
}

export const legalBackendConfig = {
  versions: {
    [LegalDocumentType.TERMS]: LEGAL_DOCUMENT_VERSION,
    [LegalDocumentType.OFFER]: LEGAL_DOCUMENT_VERSION,
    [LegalDocumentType.RECURRING_PAYMENT]: LEGAL_DOCUMENT_VERSION,
    [LegalDocumentType.MARKETING]: LEGAL_DOCUMENT_VERSION,
    [LegalDocumentType.PRIVACY_ACKNOWLEDGEMENT]: LEGAL_DOCUMENT_VERSION,
    [LegalDocumentType.PERSONAL_DATA_CONSENT]: LEGAL_DOCUMENT_VERSION,
  }
};
